server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: post
          uri: http://localhost:8081/
          Predicates:
            - Path=/api/v2/posts/**
        - id: comment
          uri: http://localhost:8082/
          Predicates:
            - Path=/api/v2/comments/**
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

custom-gateway-filter:
  headers:
    Content-Type: application/json
  error-status: UNAUTHORIZED