spring.application.name=assignment3

datasource1.url=jdbc:mysql://localhost:3306/assignment3_1lecture8
datasource1.username=root
datasource1.password=
datasource1.driverClassName=com.mysql.cj.jdbc.Driver

datasource2.url=jdbc:mysql://localhost:3306/assignment3_2lecture8
datasource2.username=root
datasource2.password=
datasource2.driverClassName=com.mysql.cj.jdbc.Driver